---
- name: Install nginx
  hosts: myservers
  become: true

  tasks:
  - name: install nginx
    command: amazon-linux-extras  install nginx1.12=latest -y
    args:
         creates: /sbin/nginx
  - name: Insert Index Page
    copy:
      src: index.html
      dest: /usr/share/nginx/html/index.html
  - name: start nginx
    service:
         name: nginx
         state: started
  - name: enable nginx
    service:
         name: nginx
         enabled: yes
